### PR TITLE
updating cyrillic components in all Roman & Italic sources

### PR DESCRIPTION
**Pull request by gferreira2**

### CODE REVIEW

**Comment by gferreira2** [comment]
hi Santiago, 
the conflicts above will go away if you pull from `googlefonts/main` first.
thanks!

**Comment by gferreira2** [comment]
hi, these are new conflicts because of the new commits in `googlefonts/main`...
I'm merging again, new commit coming soon to this pull request.

**Comment by sannorozco** [comment]
Hi @gferreira2, I cannot merge, can we have a session on Monday to figure this out?

**Comment by gferreira2** [comment]
yes, let's talk on Monday. thanks!

**Pull request closed without merging**
